spin: update build

.PHONY: build # build quartz
build:
	./build.sh

.PHONY: serve # serve quartz locally
serve:
	./serve.sh

.PHONY: update # update quartz upstream
update:
	./update.sh

include Makefile.common
